<!doctype html>

<html lang="id">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Undangan Makan Bersama</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap" rel="stylesheet">
  <style>
    :root{
      --bg:#fff8f0;
      --card:#ffffff;
      --accent:#ff6b6b;
      --muted:#666;
    }
    *{box-sizing:border-box}
    body{font-family:Inter, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial; background:linear-gradient(180deg, #fff8f0 0%, #fff 100%); margin:0; padding:24px; color:#222}
    .container{max-width:800px;margin:24px auto;padding:28px;background:var(--card);border-radius:18px;box-shadow:0 8px 30px rgba(34,34,34,0.08)}
    header{display:flex;align-items:center;gap:16px}
    .logo{width:84px;height:84px;border-radius:12px;background:linear-gradient(135deg,#ffd7d7,#fff);display:flex;align-items:center;justify-content:center;font-weight:800;color:var(--accent);font-size:28px}
    h1{margin:0;font-size:28px}
    p.lead{margin:8px 0 18px;color:var(--muted)}
    .details{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:10px}
    .card{padding:12px;border-radius:12px;background:linear-gradient(180deg,#fff,#fffaf6);border:1px solid rgba(0,0,0,0.04)}
    .card h3{margin:0 0 8px;font-size:14px}
    .card p{margin:0;color:#333}
    .note{margin-top:18px;padding:12px;border-radius:10px;background:#fffbf9;border-left:4px solid var(--accent)}
    .cta{display:flex;gap:12px;margin-top:18px}
    .btn{padding:10px 16px;border-radius:10px;text-decoration:none;font-weight:600;display:inline-block}
    .btn-primary{background:var(--accent);color:#fff}
    .btn-outline{border:1px solid var(--accent);color:var(--accent);background:transparent}
    footer{margin-top:20px;text-align:center;color:var(--muted);font-size:13px}
    @media (max-width:600px){.details{grid-template-columns:1fr}.logo{width:64px;height:64px;font-size:22px}.container{padding:18px}}
    /* print friendly */
    @media print{body{padding:0;background:#fff} .container{box-shadow:none;border-radius:0}}
  </style>
</head>
<body>
  <main class="container" role="main">
    <header>
      <div class="logo">SM</div>
      <div>
        <h1>Undangan Makan: <span id="event-name">Sedekahan Seve</span></h1>
        <p class="lead">Kami mengundang Bapak/Ibu/Saudara untuk hadir pada acara makan bersama dan syukuran kecil-kecilan.</p>
      </div>
    </header><section class="details" aria-labelledby="detail-heading">
  <div class="card">
    <h3 id="detail-heading">Waktu & Tempat</h3>
    <p><strong>Tanggal:</strong> Minggu, 14 September 2025<br>
    <strong>Waktu:</strong> 12:00 WIB — selesai<br>
    <strong>Lokasi:</strong> Rumah Seve, Jl. Contoh No. 123, Jakarta</p>
  </div>

  <div class="card">
    <h3>Tujuan Acara</h3>
    <p>Makan bersama dan bersyukur atas [sebutkan tujuan: mis. kelahiran, ulang tahun, syukuran rumah baru].
    Mohon kehadiran Bapak/Ibu untuk doa dan berkumpul bersama.</p>
  </div>
</section>

<div class="note">
  <strong>Catatan:</strong> Mohon konfirmasi kehadiran (RSVP) paling lambat 7 September 2025. Jika membawa tamu, harap informasikan jumlahnya.
</div>

<div class="cta">
  <!-- mailto link with prefilled subject -->
  <a class="btn btn-primary" href="mailto:seve@example.com?subject=RSVP%20Undangan%20Sedekahan%20Seve&body=Halo%2C%0ASaya%20mengonfirmasi%20kehadiran%20untuk%20Undangan%20Sedekahan%20Seve.%0ANama%3A%20%0BJumlah%20Tamu%3A%20%0ATerima%20kasih">Konfirmasi via Email</a>
  <a class="btn btn-outline" href="tel:+628123456789">Konfirmasi via Telepon</a>
  <a class="btn" style="background:#f5f5f5;color:#333" href="#" onclick="window.print();return false">Cetak Undangan</a>
</div>

<section style="margin-top:18px">
  <h3>Agenda Singkat</h3>
  <ul>
    <li>12:00 — Sambutan & Doa</li>
    <li>12:15 — Makan Bersama</li>
    <li>13:00 — Tukar Cerita & Foto Bersama</li>
  </ul>
</section>

<footer>
  Untuk pertanyaan: <a href="mailto:seve@example.com">seve@example.com</a> | Tel: +62 812-3456-789
</footer>

  </main>  <!-- Optional: script to quickly edit fields in the browser -->  <script>
    // Contoh: ubah data acara dari console jika perlu
    // document.getElementById('event-name').textContent = 'Nama Acara Anda';
  </script></body>
</html>
